name: Update

on:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Set up configuration
        run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
      - name: Checkout repositories
        run: |
          DIR=$(pwd)
          echo "dir="${DIR} >> $GITHUB_ENV
          cd ..
          WORKSPACE=$(pwd)
          echo "space="${WORKSPACE} >> $GITHUB_ENV
          git clone git://github.com/ome/openmicroscopy OMERO.server
          git clone git://github.com/ome/omeroweb-install
          git clone git://github.com/ome/omero-install
      - name: Update installation documentation
        run: |
          WORKSPACE=$space BUILD=false bash update.sh
